# Generated by Django 5.2.11 on 2026-02-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tryonresult',
            options={},
        ),
        migrations.AlterField(
            model_name='tryonresult',
            name='apparel_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryon_apparels/'),
        ),
        migrations.AlterField(
            model_name='tryonresult',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryon_originals/'),
        ),
        migrations.AlterField(
            model_name='tryonresult',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryon_results/'),
        ),
        migrations.AlterField(
            model_name='tryonresult',
            name='result_image_url',
            field=models.TextField(blank=True),
        ),
    ]
