# Generated by Django 5.2.11 on 2026-03-05 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_cartitem_cart'),
        ('shop', '0003_productgallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='tryon_originals/')),
                ('apparel_image', models.ImageField(blank=True, null=True, upload_to='tryon_apparels/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='tryon_results/')),
                ('result_image_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_results', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
